name = "DynamicLatex"
uuid = "27b4e752-aa1a-437f-8029-18168e97c89d"
authors = ["Nikolas Siccha and contributors"]
version = "0.1.0"

[deps]
DynamicObjects = "23d02862-63fe-4c6e-8fdb-1d52cbbd39d5"

[compat]
julia = "1"
