
project:
  title: DynamicLatex.jl
  type: website
  execute-dir: project
jupyter: julia-1.9
toc: true
toc-expand: true
toc-location: right
website:
  sidebar:
    style: "docked"
    contents: auto
format:
  html:
    code-line-numbers: true
    code-tools: true
execute:
  freeze: auto
  daemon: 3600
  error: true